variables:
 DEPLOY_TO: "website" # website or testsite, for production deploy or test deploy respectively

build_and_deploy:
 script:
  - if [[ ! -x /usr/local/bin/uglifyjs ]]; then echo "UglifyJS not executable"; exit 1; fi
  - for file in `cat conf/css.conf`; do (cat "$file"; echo) >> combined.css; done # Ensures newline separation
  - cat combined.css > schemapp.css # Future line for true minification
  - rm combined.css
  - for file in `cat conf/js.conf`; do (cat "$file"; echo) >> combined.js; done # Ensures newline separation
  - cat combined.js > schemapp.min.js #| /usr/local/bin/uglifyjs ---comments --output schemapp.min.js --source-map schemapp.min.js.map
  - rm combined.js
  - for file in `cat conf/deploy.conf`; do /bin/cp --parents -rf "$file" /var/www/$DEPLOY_TO/; done
  - /bin/cp -rf /opt/private/sqlauth.php  /var/www/$DEPLOY_TO/private/ # Copy all private PHP files in (not stored in usual repos)